// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5hgQRf-w0Zjo_yqGW1Lw0x2sTb95nkbs',
    appId: '1:956474744713:web:fce64bc631092de34dcb58',
    messagingSenderId: '956474744713',
    projectId: 'gaonexpress-1f24e',
    authDomain: 'gaonexpress-1f24e.firebaseapp.com',
    storageBucket: 'gaonexpress-1f24e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjv8H_BxcIdAfqr-4WwNVNDt7sNR2EPu4',
    appId: '1:956474744713:android:5d24d5b817f589674dcb58',
    messagingSenderId: '956474744713',
    projectId: 'gaonexpress-1f24e',
    storageBucket: 'gaonexpress-1f24e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEoohW-1sEJQHYTdqxcCWo8wtB_2yn3gU',
    appId: '1:956474744713:ios:c474d23b812dd98c4dcb58',
    messagingSenderId: '956474744713',
    projectId: 'gaonexpress-1f24e',
    storageBucket: 'gaonexpress-1f24e.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEoohW-1sEJQHYTdqxcCWo8wtB_2yn3gU',
    appId: '1:956474744713:ios:c474d23b812dd98c4dcb58',
    messagingSenderId: '956474744713',
    projectId: 'gaonexpress-1f24e',
    storageBucket: 'gaonexpress-1f24e.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5hgQRf-w0Zjo_yqGW1Lw0x2sTb95nkbs',
    appId: '1:956474744713:web:be0685f6a0acb5354dcb58',
    messagingSenderId: '956474744713',
    projectId: 'gaonexpress-1f24e',
    authDomain: 'gaonexpress-1f24e.firebaseapp.com',
    storageBucket: 'gaonexpress-1f24e.firebasestorage.app',
  );
}
